SELECT 
    A.AUTHOR_ID, 
    A.AUTHOR_NAME, 
    SALE.CATEGORY, 
    SUM(SALE.PRICE * SALE.SALES) AS TOTAL_SALES
FROM 
    AUTHOR AS A
INNER JOIN (
    SELECT 
        B.CATEGORY, 
        B.BOOK_ID, 
        B.AUTHOR_ID, 
        B.PRICE, 
        BS.SALES
    FROM 
        BOOK AS B
    INNER JOIN 
        BOOK_SALES AS BS
    ON 
        B.BOOK_ID = BS.BOOK_ID
    WHERE 
        BS.SALES_DATE LIKE '2022-01%'
) AS SALE
ON 
    A.AUTHOR_ID = SALE.AUTHOR_ID
GROUP BY 
    A.AUTHOR_ID, SALE.CATEGORY
ORDER BY 
    A.AUTHOR_ID ASC, 
    SALE.CATEGORY DESC;
