-- TREE TABLE에서 ROOT 아이템(NULL인 거)를 찾고
-- 그것을 JOIN하자.
SELECT i.ITEM_ID, i.ITEM_NAME
FROM ITEM_INFO as i
RIGHT JOIN ITEM_TREE as t
ON i.ITEM_ID = t.ITEM_ID
WHERE t.PARENT_ITEM_ID IS NULL
ORDER BY i.ITEM_ID;