-- 2022년 1월의 카테고리 별 도서 판매량을 합산하
-- 결과는 카테고리명을 기준으로 오름차순 정렬해주세요.
SELECT B.CATEGORY, SUM(SALES) AS TOTAL_SALES
FROM BOOK AS B
INNER JOIN BOOK_SALES AS BS
ON B.BOOK_ID = BS.BOOK_ID
WHERE BS.SALES_DATE LIKE "2022-01-%"
GROUP BY B.CATEGORY
ORDER BY B.CATEGORY;